config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
	root to: 'posts#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate, :except => [ :index, :show ]
  # GET /posts
  # GET /posts.json
  def index
   @posts = Post.paginate(:page => params[:page], :per_page => 4).order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
	private
	#basic authentication so only i can post things
  def authenticate
    authenticate_or_request_with_http_basic("Site Owner") do |name, password|
	  name == ENV["NAME"] && password == ENV["PASSWORD"]
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def logged_in?
		not request.authorization.nil?
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<%= stylesheet_link_tag    "/assets/pagination" %>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<%= stylesheet_link_tag    "/assets/bootstrap.min" %>
<%= javascript_include_tag "/assets/bootstrap.min" %>
<%= stylesheet_link_tag    "../assets/css/bootswatch.css" %>
<%= stylesheet_link_tag    "application.css" %>
  <head>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jaiden On Rails</title>

    <!-- Bootstrap core CSS -->
     <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
     <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet"> 

    <script src="http://heroku.github.com/template-app-bootstrap/jquery-1.7.1.min.js"></script>
    <script src="http://heroku.github.com/template-app-bootstrap/jquery.replacetext.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Jaiden On Rails</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class = "<%= 'active' if current_page?('/')%>">
			<a href="/">Home</a></li>
            <li class = "<%= 'active' if current_page?('/pages/about')%>">
			<%=link_to 'About', page_path('about')%></li>
            <li><%=mail_to "jaidengerig@gmail.com", "Contact me"%></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
	<br /><br /><br />
	<%= yield %>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div id="sidebar-wrapper">
  <p align="center">
    <br />
    <img src="http://www.gravatar.com/avatar/c40c74b23b32fadea4d1f9f2efabc777?s=150" class="img-circle" />
    <h3 class="title" align="center">
        <a href="/">Jaiden Gerig</a>
    </h3>
	<p align = "center">
	<%= link_to '<i class="fa fa-github fa-lg"></i>'.html_safe, 'https://github.com/jaideng123'%>  &nbsp;
    <%= link_to '<i class="fa fa-twitter fa-lg"></i>'.html_safe, 'https://twitter.com/jaideng123'%> &nbsp;
    <%=mail_to "jaidengerig@gmail.com", '<i class="fa fa-envelope fa-lg"></i>'.html_safe%>
    </p>
  </p>
</div>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container-fluid">
	  <ul class="nav nav-tabs" style="margin-bottom: 15px;">
	    <li class="active"><a href="#bio" data-toggle="tab">Bio</a></li>
	    <li class=""><a href="#resume" data-toggle="tab">Resume</a></li>
	  </ul>
	  <div id="myTabContent" class="tab-content">
	    <div class="tab-pane fade active in" id="bio">
	      <p style='max-width: 600px;'>
		  Hailing from Austin, Texas, Jaiden Gerig is a student at Texas A&M University 
		  where he is currently studying for a Bachelors degree in Computer science.
		  His professional interests include web and commercial software development.
		  Whenever he's not studying, coding, or scarfing down burgers, Jaiden also enjoys video-games,
		  live music, and Game of Thrones.
		  
          </p>
        </div>
	    <div class="tab-pane fade" id="resume">
	      <h2>Resume</h2>
          <iframe src="https://docs.google.com/viewer?srcid=0Bz8zxihkODz-Q0lxbHBJSTdwd2c&pid=explorer&efh=false&a=v&chrome=false&embedded=true" id="docviewer"></iframe>
	    </div>
	</div>
   </div>
  </div>
</div>  

app/views/pages/resume.html.erb
<h2>Resume</h2>
<iframe src="https://docs.google.com/viewer?srcid=0Bz8zxihkODz-Q0lxbHBJSTdwd2c&pid=explorer&efh=false&a=v&chrome=false&embedded=true" style="position: absolute; height: 90%; max-width: 90%; width: 800px;"></iframe>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%=f.cktext_area :content, :class => 'ckeditor'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>
p
{
  white-space:pre-wrap;
} 
</style>
<% @posts.each do |post| %>
  <div class="row" style ='width:95%; max-width: 800px; margin-left: 15px;'>
    <h2>
      <%= link_to post.title, post %>
    </h2>
    <p style = 'white-space: initial;'>
      <i class="fa fa-clock-o"></i> Posted: <%=l post.created_at, :format=> :post_datetime %>
    </p>
    <span style="line-height:60px"></span> 
    <%= raw post.content.split("\n", 2)[0]%>
    <br />
	
      <% if logged_in?%>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%end%>
		
  </div>
<% end %>
<%= will_paginate @posts, :class => 'digg_pagination' %>
<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<style>
p
{
  white-space:pre-wrap;
} 
</style>
<div class="row" style ='width:95%; max-width: 800px; margin-left: 15px;'>
  <h2 style = 'color: FireBrick;'>
    <%=@post.title%>
  </h2>
  <p style = 'white-space: initial;'>
    <i class="fa fa-clock-o"></i> Posted: <%=l @post.created_at, :format=> :post_datetime %>
  </p>
  <span style="line-height:60px"></span> 
  <%= raw @post.content%>
  <br />
 
  <% if logged_in?%>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>
		
</div>
<div id="disqus_thread" style ='width:95%; max-width: 800px;'></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'jaidenonrails'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
<br>